### ISSUE TITLE
Projections for year classes in multi stock models

### ISSUE THREAD

**Issue by Craig44** [Casal2/CASAL2#107]
Future development of the assessment should explore how to include covariance between different stock year-class strengths. (i.e. HOKI East and West Stock)
This would better reflect the relative status of future trends between East and West stocks. There is an appreciable correlation (~0.7) between the year-class strength estimates from the assessment that is not currently being reflected in the projections as they are sampled independently of each other. Furthermore this exercise should continue to include some configuration options that incorporate the auto-correlated nature of the recruits as may prove appropriate.

**Comment by Casal2** [comment]
Closing issue. Been a few years and will be placed on a roadmap if required.
