### ISSUE TITLE
Report the gradient after each MCMC iteration.

### ISSUE THREAD

**Issue by Craig44** [Casal2/CASAL2#135]
One of the new MCMC algorithms (HMC)
[HMC_mcmc.txt](https://github.com/NIWAFisheriesModelling/CASAL2/files/303591/HMC_mcmc.txt)

 that we are looking at implementing this year needs to know the gradient of the posterior which then informs the generation of the following candidates. @Zaita are we able to use a minimiser to evaluate the gradient during an MCMC iteration. Attached is a simple R script that runs through the algorithm, to show the example

**Comment by Zaita** [comment]
No. You need to have a function put in to the Utilities or MCMC to generate the gradient. There is currently no generic way to do this as not all minimisers need/use a gradient.

**Comment by Craig44** [comment]
Can we choose just one of the minimisers (e.g. CPPAD) and put in the utilities? so we can access its functionality?

**Comment by Zaita** [comment]
Every time you calculate gradient it will cost n iterations where n is the number of estimates. This is a huge slowdown

**Comment by Zaita** [comment]
Any update on this or should I close it?

**Comment by alistairdunn1** [comment]
Keep it. While each iteration will be slower, the number of total iterations for an mcmc should be an order of magnitude of two shorter. Note we probably don't need to re-generate the differentiation, just recompute the gradient using the existing differentiation

**Comment by Zaita** [comment]
I'll try and implement the gradient calculation from the FMM/Numerical differences minimiser then.Will try and get this done Saturday

**Comment by Casal2** [comment]
Closing. Casal2 now has a generic multi-threaded gradient calculation that is implemented in the Hamiltonian Monte Carlo MCMC
