### ISSUE TITLE
methods to improve mcmc algorithms e.g. simulated annealing and parallel tempering

### ISSUE THREAD

**Issue by largek** [Casal2/CASAL2#178]
[PT_MCMC_KLarge.pdf](https://github.com/NIWAFisheriesModelling/CASAL2/files/915399/PT_MCMC_KLarge.pdf)

MCMC methods can perform poorly when they are used to simulate samples from multimodal distributions. Incorporating techniques such as simulated annealing and parallel tempering (PT) can improve mixing of the MCMC algorithm leading to faster convergence of the sampling chain to the target distribution. 
Back in 2012, as part of an Honours project, I coded up a univariate Normal mixture example in R to illustrate the PT process.  The attached document is the write-up of that project with code included in the appendix.

**Comment by Craig44** [comment]
Thought I would add to this, not the same method but here are other methods for parallel MCMC methods

[Uploading smith_parellel_MCMC.pdf…]()

**Comment by Craig44** [comment]
If anyone gets around to it, the NUTs algorithm coded into ADMB is here https://github.com/admb-project/admb/blob/master/src/nh99/nuts.cpp

**Comment by Casal2** [comment]
Closing issue. Been a few years and will be placed on a roadmap if required.
