### ISSUE TITLE
Single-stepping parameters that are year based maps

### ISSUE THREAD

**Issue by Craig44** [Casal2/CASAL2#180]
One of the issues I came across the other day was when I was trying to single step the catches parameter from the instantaneous mortality process. an example of the parameter that is accepted is process[Instantaneou_Mortality].fishery_fisherywest(2001)  which gets asked to be updated every year but obviously you only want it to be updated once for 2001. there is no point updating this parameter in 2012 because it wont be used.
Business rule.
Only update parameters of the following  types
- single
- map sting 
- map unsigned where the unsigned refers to a year
- a specific vector element.

The parameter type (map unsigned) is the only parameter type that won't require the index when defining it e.g instead of referencing it as process[Instantaneou_Mortality].fishery_fisherywest(2001) , you reference it as process[Instantaneou_Mortality].fishery_fisherywest and let the year that it is updated be the index.

**Comment by Casal2** [comment]
Closing issue. Been a few years and will be placed on a roadmap if required.
