### ISSUE TITLE
Take a posterior sample of parameters and calculate the normalising constant.

### ISSUE THREAD

**Issue by Craig44** [Casal2/CASAL2#219]
I am looking at Bayesian model averaging to allow us to add structural uncertainty into management quantities such as %b0 etc,

In order to do this we need to approximate the normalizing constant that we ignore when undertaking the MCMC (we ignore it by assuming that the posterior is proportional to objective function) and thus saving a most likely non-tractable integral. However in the realm of model averaging and bayes factors we need this normalizing constant which is some times referred to as 'model evidence'. There are many approximations to this see Diciccio et.al (1997) one that I think seems fairly easy to implement is the "Importance Sampling method" from Gelfand and Dey (1994). Which basically says the normalizing constant is a function of the objective function and 'some'  importance density (which I will make normal or T-distribution for now). So questions for the dev-team are how best to implement this, I am just spit-balling here, open to suggestions. The importance density can have mean and co variance that is user defined or from a MPD run

- A new run mode that must take a -i 
- A report that does it all
- A inline parameter (--calculate_constant) that automatically generates a report and does the calculation.

**Comment by Casal2** [comment]
Closing issue. Been a few years and will be placed on a roadmap if required.
