### ISSUE TITLE
add predation as electivity

### ISSUE THREAD

**Issue by smormede** [Casal2/CASAL2#251]
Predation currently has Holling function only. Copy the electivity predation module from SPM, required urgently.

**Comment by Zaita** [comment]
This process already exists as "Mortality Prey Suitability"

type: mortality_prey_suitability

**Comment by SamikDatta** [comment]
Jinging is now testing this module, fingers crossed there is nothing left to do and this issue can be closed.

**Comment by Zaita** [comment]
@SamikDatta How is this going?

**Comment by SamikDatta** [comment]
I'm about to submit the changes to the manual, copied and adapted from the relevant section in SPM. @Zaita - I'm not 100% sure if any of the variable names have changed when moving this functionality to Casal2 (reading through the .cpp and .h file for MortalityPreySuitability it _looks_ the same, although I can't be positive. Does Jingjing have a unit test for it? In which case it will tell me if I need to modify the manual further.

**Comment by Zaita** [comment]
No unit tests were implemented when this process was ported.

**Comment by SamikDatta** [comment]
I'll check with Jingjing if she has some kind of test ready which we can incorporate.

**Comment by SamikDatta** [comment]
Resubmitted now, @Zaita , should be fine in terms of the file history.

**Comment by Casal2** [comment]
Closing issue. Been a few years and will be placed on a roadmap if required.
