### ISSUE TITLE
Multi-state selectivity associated with a fishery, e.g. discards

### ISSUE THREAD

**Issue by hoyles** [Casal2/CASAL2#254]
Ian suggests an approach in this paper:
Andre E. Punt, David C. Smith, Geoff N. Tuck, Richard D. Methot (2006). Including discard data in fisheries stock assessments: Two case studies from south-eastern Australia. Fisheries Research 79. 239–250. 

The requirement is to estimate selectivities to fit (directly or indirectly) size data sampled on vessels (captured = retained + discards) and size data sampled in the sheds (retained). Other applications may need to distinguish a third class of fish that are trawled but then escape through the mesh, but suffer some mortality as a result.

**Comment by Casal2** [comment]
Closing issue. Been a few years and will be placed on a roadmap if required.
