### ISSUE TITLE
Units of length/weight relationships

### ISSUE THREAD

**Issue by mkienzle** [Casal2/CASAL2#270]
The length/weight relationships (coded in LengthWeights/Common/Basic.cpp) defines a single string to specify the unit (presumably for weight because it can represents only units of mass - tonnes, kgs, ...).

In a length/weight relationship, there are 2 variables, each with a different unit: one length variable in unit of length (millimeters, centimeters, meters) and one weight in unit of mass. The unit of length is presumably assumed by the software to be centimeters for the moment.

CASAL2, could be improved by requiring the user to define what is the unit of length for the measurements used to define the relationship between weight and length.

**Comment by largek** [comment]
Also need to review the documentation to check that units (and their use) are clearly defined.

**Comment by Casal2** [comment]
Closing issue. Been a few years and will be placed on a roadmap if required.
