### ISSUE TITLE
Add double logistic selectivity...

### ISSUE THREAD

**Issue by SamikDatta** [Casal2/CASAL2#291]
This already exists in CASAL - Ian wants the same functionality for Casal2, to take into account pot selectivity for blue cod (upper age/length selectivity), so asymptoting from 1 to 0 as age/length increases.

**Comment by largek** [comment]
This issue migrated to GitLab (issue #40) but not addressed as part of V1.0 development.

**Comment by Casal2** [comment]
Closing issue. Been a few years and will be placed on a roadmap if required.
