### ISSUE TITLE
 Update MCMC functionality to allow for recalculating the covariance matrix more than once (GitLab issue #30)

### ISSUE THREAD

**Issue by largek** [Casal2/CASAL2#335]
CASAL allows for recalculating and adjusting the covariance matrix during an MCMC chain with the option "adaptive_covariance: Should the MCMC covariance matrix be altered during the chain?" and the associated options, e.g., "adapt_covariance_at: At which iteration numbers can the MCMC covariance matrix be altered?".

Casal2 allows for recalculating and adjusting the covariance matrix during an MCMC chain with the option "adapt_covariance_matrix_at". However, this adjustment can occur once only: https://git.niwa.co.nz/fisheries/modelling/casal2-development/blob/master/CASAL2/source/MCMCs/Common/IndependenceMetropolis.cpp#L451

This functionality needs to be enhanced to match the CASAL functionality and the similar Casal2 functionality for "adapt_stepsize_at" so that the adjustment of the covariance matrix can occur more than once.

Screenprint: [Update MCMC functionality to allow for recalculating the covariance matrix more than once (#30) · Issues · Fisheries _ modelling _ Casal2 Development · GitLab.pdf](https://github.com/NIWAFisheriesModelling/CASAL2/files/5773185/Update.MCMC.functionality.to.allow.for.recalculating.the.covariance.matrix.more.than.once.30.Issues.Fisheries._.modelling._.Casal2.Development.GitLab.pdf)

**Comment by Casal2** [comment]
Closing issue. Been a few years and will be placed on a roadmap if required.
