### ISSUE TITLE
Review classes that need more validating than the others (aka Craig's suspiciously coded classes). (GitLab issue #32)

### ISSUE THREAD

**Issue by largek** [Casal2/CASAL2#337]
There are some classes that are well tested through comparisons with CASAL models, but there are fringe classes that I deem suspicious and should be the focus of priority testing **if** they are to be included in the release of Version 1.

**Initialisation/Cinitial**

In the CASAL code, when cinitial is applied, it then generates the derived quantities Rinitial and Binitial in the system. These are important for Recruitment classes and have specific consequences. I don't believe we have dealt with the Binitial and Rinitial for Casal2 models and so am suspicious of this class in Casal2.

**EstimateTransformations**

Needs more testing in general, there are three CASAL assessments which exhibit estimate transformations 

- Hoki with B0_East & BO_West parameterised as theta1 = log(B0_East + BO_West) theta2 = proportion of total belonging to B0_east (`LogSum.cpp`) 
- SBW estimate natural mortality average difference (`AverageDifference.cpp`) 
- HAK one of the HAK assesments estimates proportion of recruits `p_male` that is a simplex `p_female = 1 - p_male`  (`SumToOne.cpp`) also very related to this is issue #54

Screenprint: [Review classes that need more validating than the others (aka Craig's suspiciously coded classes). (#32) · Issues · Fisheries _ modelling _ Casal2 Development · GitLab.pdf](https://github.com/NIWAFisheriesModelling/CASAL2/files/5773197/Review.classes.that.need.more.validating.than.the.others.aka.Craig.s.suspiciously.coded.classes.32.Issues.Fisheries._.modelling._.Casal2.Development.GitLab.pdf)

**Comment by Casal2** [comment]
Closing issue. Been a few years and will be placed on a roadmap if required.
