### ISSUE TITLE
Validate the projection functionality with the Test Cases

### ISSUE THREAD

**Issue by NIWAFisheriesModelling** [Casal2/CASAL2#377]
Validate the projection functionality with the Test Cases: comparison of CASAL vs Casal2 for 6 models

MPD -> MCMC -> projections

- [ ] rerun the CASAL and Casal2 models in MCMC mode
- [ ] update CASAL and Casal2 MCMC output and reports
- [ ] set up CASAL and Casal2 projection functionality
- [ ] review CASAL and Casal2 projection functionality so that they are the same or equivalent
- [ ] create R Markdown report for comparing the CASAL and Casal2 projections

**Comment by Casal2** [comment]
Closing issue. Been a few years and will be placed on a roadmap if required.
