### ISSUE TITLE
Complete the comparisons of Casal2 and the NOAA stock assessment model comparison project(s)

### ISSUE THREAD

**Issue by NIWAFisheriesModelling** [Casal2/CASAL2#378]
Some work has been completed setting up the R code to run Casal2 for a set of simulated data from the NOAA stock assessment model comparison project. The files are in the subdirectory TestCases/secondary. The URL was https://github.com/Bai-Li-NOAA/Stock-Assessment-Model-Comparison-Project, and is now https://github.com/Bai-Li-NOAA/Model_Comparison_Paper.

This work can be used to validate Casal2 functionality.

There is also a (related? updated?) project at https://github.com/Bai-Li-NOAA/Age_Structured_Stock_Assessment_Model_Comparison.

**Comment by Casal2** [comment]
Closing issue. Been a few years and will be placed on a roadmap if required.
