### ISSUE TITLE
ADD initial mean length at age into the data table

### ISSUE THREAD

**Issue by Craig44** [Casal2/CASAL2#384]
**Describe exactly what you would like to see in an upcoming release**
Currently CASAL and Casal2 calculate mean length at age as the average over the supplied values. I think it would be a good addition for users to supply values that are used during the initialisation phase. This would include changing the input table from 
```
table data
year 1 2 3 4 5
1900 12 16.3 20 23.3 26.3 
1991 12 16.3 20 23.3 26.3 
```

to 
```
table data
year 1 2 3 4 5
initial 12 16.3 20 23.3 26.3 
1900 12 16.3 20 23.3 26.3 
1991 12 16.3 20 23.3 26.3 
```

This will give users the flexibility to bypass any internal interpolations that may not be well documented.

Something to consider how to deal with multiple initialisation phases.

- A second table? table "initialisation_data" with labels ("years") equal to the labels of initialisation_phase's?
- Add rows into current table with label of initialisation phases.

**Comment by Casal2** [comment]
Closing issue. Been a few years and will be placed on a roadmap if required.
