### ISSUE TITLE
Verifies to add

### ISSUE THREAD

**Issue by Craig44** [Casal2/CASAL2#385]
- [ ]  Don't allow users to specify ratio q with qs of type nuisance. The analytical solution to nuisance haven't (to my knowledge) accounted for objective score contributions from the ratio q penalty/additional_prior. This means the analytical solution will be incorrect for this case. So I suggest we just don't allow users have this set up
- [x] GrowthIncrements check the growth process is applies in all years that have growth_increments_.time_step_proportions > 0
 
- [x] Don't allow multiple usage of parameter in the same command for @estimates.
  
- [x] Verify time-step manager. Currently we verify if a process i.e. ageing is in the model config, but this doesn't verify if it is in the annual cycle.

**Comment by Casal2** [comment]
Closing issue. Been a few years and will be placed on a roadmap if required.
