### ISSUE TITLE
Self test functionality idea/Alternatively Write a utility program

### ISSUE THREAD

**Issue by Craig44** [Casal2/CASAL2#393]
`casal2 --selftest n_iter -c OM -C EM`   `n_iter` is the number of simulations per input parameter set  i.e., `-i`
```
@report self_test
type self_test
directory 
exclude_observations
simulation_observation_file_name
estimation_file_name
```

casal2 will iterate over all observations simulate observations into a file `simulation_observation_file_name`.

preprocess
- create a csl2 file excluding observations (create a new report to print the full configuration file used in a run) allow subcommand to drop components i.e. observations.

simulate
- for each row of `-i`
- simulate `n_iter` observations
- cache extension for reading during estimation.

estimation
- Load config created in preprocess, and add to this. !include for simulated input observations
- run estimation and pipe output into a `estimation_file_name`

## future ideas
MCMC and MPD?
Alternative estimation model configs

**Comment by Casal2** [comment]
Merged
