### ISSUE TITLE
ADD tag test case sexed and unsexed.

### ISSUE THREAD

**Issue by Craig44** [Casal2/CASAL2#398]
Simulate data for this comparison

**Comment by Craig44** [comment]
This has been validated in the following CCAMLR publication. There is an example Casal2 configuration file in TestModels for both sexed and unsexed.

Dunn, A.; Grüss, A.; Devine, J.A.; Miller, C.; Ziegler, P.; Maschette, D.; Earl, T.; Darby, C.; Massiot-Granier, F. (2022). Integrated toothfish stock assessments using Casal2. WG-SAM-2022/14. CCAMLR, Hobart, Australia, 20 p.

**Comment by Craig44** [comment]
Although, this functionality has been simulation tested, we still need to build CASAL and Casal2 side by side configs for training and translation purposes.

**Comment by NIWAFisheriesModelling** [comment]
There are some tag release and recapture data in the [Test Case SCI](https://github.com/NIWAFisheriesModelling/Casal2-supporting-information/tree/main/TestCases/primary/SCI).

Please add some CASAL and Casal2 comparison metrics for tagging to the Test Case SCI MPD report.

**Comment by Casal2** [comment]
Closing issue. Been a few years and will be placed on a roadmap if required.
