### ISSUE TITLE
Selectivity class that can change parameterisation over time

### ISSUE THREAD

**Issue by Craig44** [Casal2/CASAL2#408]
**Describe exactly what you would like to see in an upcoming release**
With recent gear changes in fisheries we have been splitting out multiple fisheries to account for changing selectivities. However, I think it would be cleaner to deal with this using selectivities.

I would like to have a selectivity class that takes selectivity labels for each model year. This way we can switch from a double normal to logistic selectivity curve or vice versa for a fishery selectivity during the model years.

**Comment by Craig44** [comment]
The thing I didn't like and should also be considered is. Each execute for each age, time-step, year it does a find call which may be ineffecieint.
It would be nice if we had a "year_ndx" accessor from the model `model_->year_ndx()` and save the selectivity pointer in a year indexed vector during the build. That way each execute `get_value` call can be an quick look up i.e.,

`selectivities_by_year_[model_->year_ndx()]->get_value(...)`

**Comment by Casal2** [comment]
Closing issue. Been a few years and will be placed on a roadmap if required.
