### ISSUE TITLE
Category format and short hand syntax consideration

### ISSUE THREAD

**Issue by Craig44** [Casal2/CASAL2#412]
When categories `format` have a numeric first value an example is given below for when tagging is in the partition
```
@categories
format		tag.region
names		untagged,214,215,216,217,218,219,220,221,222,223.R1,R2,R4
age_lengths	 age_length*44  # growth by stock, not area
```

This will mess up the short hand syntax usage particularly the `*` multiplier usage e.g.,

` 214.R1 * 3     214.R2 * 3     214.R3* 3 `

Casal2 will read that line as

` 214.R1*3214.R2*3214.R3*3 `

because it removes the spaces which will misinterpret the multiplier number. 

## solution

Ban category labels that start with a number

**Comment by Zaita** [comment]
This has been fixed.
