### ISSUE TITLE
ReportTabular for type selectivity in an age-based model when the selectivity is length based

### ISSUE THREAD

**Issue by Craig44** [Casal2/CASAL2#413]
Currently when Casal2 writes a tabular report for the above situation it creates a empty report like that shown below.

![image](https://user-images.githubusercontent.com/13144077/230243385-caa12e98-6a04-4ae3-937c-5d19e0028741.png)

We either need to fix the Source code so it doesn't do this. Or change the extract.tabular in the casal2 R package so that it recognises an empty report and ignores it.

**Comment by Zaita** [comment]
This should be fixed in r4Casal2 package.

**Comment by alistairdunn1** [comment]
This should refer to the Casal2 R library (extract.tabular function ), not the r4casal2 library
