### ISSUE TITLE
Note regarding standard errors from Chris Francis

### ISSUE THREAD

**Issue by largek** [Casal2/CASAL2#63]
From: Chris Francis [mailto:chris.francis@clear.net.nz] 
Sent: Tuesday, 13 January 2015 9:47 a.m.
To: Alistair Dunn; Ian Doonan
Subject: S.e.s in CASAL2

Hi Alistair,

When we last spoke you asked me if I could think of anything else that could usefully be added to CASAL2.   

Something that's just occurred to me that I think that assessment scientists might find useful is the ability, in MPD runs, to output s.e.s of both model parameters and derived quantities, as is possible in ADMB.  I'd never been sure how that was done, until I read the following paper, which makes it clear that it's just an application of the delta method.  
Magnusson, Arni, André E. Punt, and Ray Hilborn. "Measuring uncertainty in fisheries stock assessment: the delta method, bootstrap, and MCMC." Fish and Fisheries 14.3 (2013): 325-342.

The delta method formula for a variance of a function of a vector of parameters (see Ch. 1 of Seber's book The Estimation of Animal Abundance ...)  uses variances & covariances of model parameter (estimated from the inverse Hessian) and partial derivatives of the function with respect to the model parameters (which are evaluated in the automatic differentiation).  Straightforward in principle, but needs someone savvy to see how to implement it.  

Best wishes for 2015,

Chris

**Comment by Craig44** [comment]
Add reference paper for looking in at a later date

[Magnusson_et_al-2013-Fish_and_Fisheries.pdf](https://github.com/NIWAFisheriesModelling/CASAL2/files/454343/Magnusson_et_al-2013-Fish_and_Fisheries.pdf)

**Comment by Craig44** [comment]
I think this should also be high on the priority list, it will allow us to report uncertainty on derived quantities for MPD estimation, which currently we cannot do. Could be especially useful when MCMC becomes slow.

**Comment by Zaita** [comment]
@amart What is status/priority for this?

**Comment by amart** [comment]
@Zaita I think that this is an important feature. ADMB has a separate class for derived quantities so that they will be part of the covariance structure.

**Comment by Casal2** [comment]
Closing issue. Been a few years and will be placed on a roadmap if required.
